spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/store?serverTimezone=GMT%2B8
    username: root
    password: root123

mybatis:
  mapper-locations: classpath:mapper/*.xml

# SpringBoot读取配置文件: @Value("${user.address.max-count}")
user:
  address:
    max-count: 20
#  服务器向客户端不响应为null的属性
#spring.jackson.default-property-inclusion=NON_NULL

# server.servlet.context-path=/store
# spring.servlet.multipart.maxFileSize=10MB   //单个文件最大限制
# spring.servlet.multipart.maxRequestSize=15MB    //总文件文件最大限制